---

- environment: "production"

  variables:
    region: "us-east-1"
    vpc: "vpc-xxxxxxxx"

  instances:
    
    - name: "test"
      type: "t2.micro"
      keypair: "test"
      security_group: "generator-test"

    - name: "test2"
      type: "t2.micro"
      keypair: "test"
      security_group: "generator-test"

  security_groups:

    - name: "generator-test"
      description: "test sg for terraform auto-generation"
