---

variables:
  region: "us-east-1"

instance:
  name: "test"
  type: "t2.micro"
  vpc: ""
  subnet: 
    east-1a: "" 
    east-1b: ""
    east-1c: ""
    east-1d: ""
  ami: "ami-1c221e76"
  ssh_user: "centos"
  keypair: ""

security_group:
  prefix: "test"
  description: "test sg for terraform auto-generation"
  services:
    - "22"
    - "80"
    - "443"
